const stage = document.querySelector('.home-page .portrait-stage');
const hero = document.querySelector('.home-page .home-hero');

if (stage && hero) {
  stage.classList.add('robot-cinematic-stage');
  hero.classList.add('robot-cinematic-hero');

  const style = document.createElement('style');
  style.id = 'robot-cinematic-styles';
  style.textContent = `
    .home-page .robot-cinematic-hero{min-height:250svh;padding:0;display:block;overflow:visible;background:radial-gradient(circle at 8% 8%,rgba(156,255,87,.18),transparent 28%),radial-gradient(circle at 92% 18%,rgba(97,216,255,.17),transparent 28%),var(--paper)}
    .home-page .robot-cinematic-hero>.hero-grid-v2{position:sticky;top:0;min-height:100svh;padding-top:108px;padding-bottom:42px;align-items:center;z-index:2}
    .home-page .robot-cinematic-stage{position:relative;min-height:680px;display:grid;place-items:center;isolation:isolate}
    .home-page .robot-cinematic-stage>.portrait-frame,.home-page .robot-cinematic-stage>.floating-chip,.home-page .robot-cinematic-stage>.orbit-ring{display:none!important}
    .robot-cinematic-shell{position:relative;width:min(100%,610px);height:650px;overflow:hidden;border-radius:44px;border:1px solid rgba(10,15,24,.11);background:#f5f2e9;box-shadow:0 34px 90px rgba(10,15,24,.16);transform:rotate(.7deg);isolation:isolate}
    .robot-cinematic-shell:before{content:"";position:absolute;inset:0;z-index:2;pointer-events:none;background:linear-gradient(180deg,rgba(255,255,255,.2),transparent 22%),radial-gradient(circle at 72% 20%,rgba(97,216,255,.08),transparent 30%);mix-blend-mode:screen}
    .robot-cinematic-shell:after{content:"";position:absolute;inset:0;z-index:9;pointer-events:none;border-radius:inherit;box-shadow:inset 0 0 0 1px rgba(255,255,255,.58),inset 0 -90px 120px rgba(10,15,24,.025)}
    .robot-cinematic-canvas{width:100%;height:100%;display:block}.robot-hud{position:absolute;inset:0;z-index:6;pointer-events:none;font-family:"DM Sans",sans-serif;color:#0a0f18}
    .robot-hud-top{position:absolute;left:22px;right:22px;top:22px;display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.robot-hud-card{padding:11px 13px;border:1px solid rgba(10,15,24,.1);background:rgba(247,245,238,.78);backdrop-filter:blur(14px);border-radius:16px;box-shadow:0 12px 30px rgba(10,15,24,.07)}
    .robot-hud-card span,.robot-hud-status,.robot-scroll-note,.robot-stage-label small,.robot-stat span{font-size:8.5px;font-weight:900;letter-spacing:.11em;text-transform:uppercase}.robot-hud-card strong{display:block;margin-top:3px;font:700 14px/1.1 "Space Grotesk",sans-serif;letter-spacing:-.025em}
    .robot-hud-status{display:flex;align-items:center;gap:7px;padding:9px 11px;border-radius:999px;background:rgba(156,255,87,.82);border:1px solid rgba(10,15,24,.1)}.robot-hud-status i{width:7px;height:7px;border-radius:50%;background:#168c3e;box-shadow:0 0 0 0 rgba(22,140,62,.28);animation:robotSignal 1.8s infinite}
    .robot-stage-label{position:absolute;left:22px;bottom:24px;max-width:280px;padding:14px 15px;border-radius:18px;background:rgba(10,15,24,.90);color:#fff;border:1px solid rgba(255,255,255,.12);box-shadow:0 18px 38px rgba(10,15,24,.16);backdrop-filter:blur(12px);opacity:0;transform:translateY(10px);transition:opacity .25s ease,transform .25s ease}.robot-stage-label.is-active{opacity:1;transform:none}.robot-stage-label small{color:#9cff57;display:block;margin-bottom:5px}.robot-stage-label strong{font:700 clamp(22px,2.2vw,31px)/.95 "Space Grotesk",sans-serif;letter-spacing:-.045em}.robot-stage-label p{font-size:11px;line-height:1.45;color:#d5dae1;margin:8px 0 0}
    .robot-scroll-note{position:absolute;right:22px;bottom:23px;padding:9px 11px;border-radius:999px;background:rgba(247,245,238,.8);border:1px solid rgba(10,15,24,.08);color:#646b74;backdrop-filter:blur(10px)}
    .robot-stats{position:absolute;right:22px;top:88px;display:grid;gap:8px;width:150px}.robot-stat{padding:10px 11px;border-radius:14px;background:rgba(247,245,238,.72);border:1px solid rgba(10,15,24,.08);backdrop-filter:blur(12px);box-shadow:0 10px 22px rgba(10,15,24,.05)}.robot-stat strong{display:block;font:700 14px/1 "Space Grotesk",sans-serif;margin-top:4px}
    .robot-progress{position:absolute;left:22px;right:22px;bottom:10px;height:2px;background:rgba(10,15,24,.10);overflow:hidden;border-radius:999px}.robot-progress b{display:block;width:0;height:100%;background:linear-gradient(90deg,#ff5f57,#875cff,#61d8ff);transform-origin:left center}
    .robot-loader{position:absolute;inset:0;z-index:8;display:grid;place-items:center;background:#f5f2e9;transition:opacity .55s ease,visibility .55s ease}.robot-loader.is-ready{opacity:0;visibility:hidden}.robot-loader-inner{text-align:center;width:min(76%,320px)}.robot-loader-inner b{display:block;font:700 clamp(29px,3vw,42px)/.96 "Space Grotesk",sans-serif;letter-spacing:-.05em}.robot-loader-inner span{display:block;margin-top:8px;font-size:9px;font-weight:900;letter-spacing:.12em;text-transform:uppercase;color:#6b7280}.robot-loader-track{height:3px;margin-top:18px;background:#dedbd2;border-radius:999px;overflow:hidden}.robot-loader-track i{display:block;width:6%;height:100%;background:#875cff;transition:width .18s ease}
    .robot-model-warning{position:absolute;left:50%;bottom:78px;transform:translateX(-50%);z-index:7;display:none;max-width:78%;padding:8px 11px;border-radius:999px;background:rgba(255,110,91,.9);color:white;font-size:8px;font-weight:900;letter-spacing:.08em;text-transform:uppercase;text-align:center}
    @keyframes robotSignal{70%{box-shadow:0 0 0 9px rgba(22,140,62,0)}100%{box-shadow:0 0 0 0 rgba(22,140,62,0)}}.home-page .robot-cinematic-hero .hero-intro{transition:opacity .3s ease,transform .3s ease}.home-page .robot-cinematic-hero .scroll-cue{position:sticky;bottom:20px;z-index:4}
    @media(max-width:1100px){.home-page .robot-cinematic-stage{min-height:610px}.robot-cinematic-shell{height:590px}}@media(max-width:900px){.home-page .robot-cinematic-hero{min-height:auto;padding:110px 0 54px}.home-page .robot-cinematic-hero>.hero-grid-v2{position:relative;min-height:auto;padding-top:0;padding-bottom:0}.robot-cinematic-shell{width:min(100%,760px);height:550px;transform:none}.home-page .robot-cinematic-stage{min-height:570px}.robot-stats{display:none}}@media(max-width:560px){.robot-cinematic-shell{height:480px;border-radius:28px}.home-page .robot-cinematic-stage{min-height:500px}.robot-hud-top{left:13px;right:13px;top:13px}.robot-hud-card{max-width:190px}.robot-stage-label{left:13px;right:13px;bottom:18px;max-width:none}.robot-scroll-note{display:none}.robot-progress{left:13px;right:13px;bottom:8px}}@media(prefers-reduced-motion:reduce){.robot-hud-status i{animation:none!important}.home-page .robot-cinematic-hero{min-height:auto}.home-page .robot-cinematic-hero>.hero-grid-v2{position:relative}}
  `;
  document.head.appendChild(style);
  stage.insertAdjacentHTML('beforeend', `<div class="robot-cinematic-shell" aria-label="Interactive 3D VEX robot engineering scene"><canvas class="robot-cinematic-canvas"></canvas><div class="robot-hud" aria-hidden="true"><div class="robot-hud-top"><div class="robot-hud-card"><span>VERTEX / PUSH BACK</span><strong>Engineering in motion.</strong></div><div class="robot-hud-status"><i></i> LIVE SIMULATION</div></div><div class="robot-stats"><div class="robot-stat"><span>MODEL</span><strong>Onshape CAD</strong></div><div class="robot-stat"><span>CONTROL</span><strong>C++ / Odom</strong></div><div class="robot-stat"><span>LOOP</span><strong>Test → Rebuild</strong></div></div><div class="robot-stage-label is-active" data-scene="0"><small>01 / BUILD</small><strong>Start with the machine.</strong><p>CAD, drivetrain geometry, mechanisms, and the constraints that turn an idea into a physical system.</p></div><div class="robot-stage-label" data-scene="1"><small>02 / TEST</small><strong>Make the robot prove it.</strong><p>The red trajectory is not decoration — it represents the autonomous path, where every miss becomes data.</p></div><div class="robot-stage-label" data-scene="2"><small>03 / DIAGNOSE</small><strong>Follow the error, not the ego.</strong><p>Observe drift, alignment, sensor behavior, and field interaction. Then change the design or control system.</p></div><div class="robot-stage-label" data-scene="3"><small>04 / REBUILD</small><strong>The next version should know why it exists.</strong><p>Iteration is the point: mechanical redesign, new code, cleaner decisions, and another run.</p></div><div class="robot-scroll-note">SCROLL · FLY THROUGH THE SYSTEM</div><div class="robot-progress"><b></b></div></div><div class="robot-model-warning">3D CAD asset missing · showing fallback robot</div><div class="robot-loader"><div class="robot-loader-inner"><b>Loading the robot.</b><span>Initializing CAD · field · autonomous path</span><div class="robot-loader-track"><i></i></div></div></div></div>`);

  const shell=stage.querySelector('.robot-cinematic-shell'),canvas=stage.querySelector('.robot-cinematic-canvas'),loaderEl=stage.querySelector('.robot-loader'),loaderBar=stage.querySelector('.robot-loader-track i'),warning=stage.querySelector('.robot-model-warning'),progressBar=stage.querySelector('.robot-progress b'),stageLabels=[...stage.querySelectorAll('.robot-stage-label')],intro=hero.querySelector('.hero-intro'),reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches,clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v)),smooth=t=>t*t*(3-2*t);

  async function init3D(){
    const THREE=await import('https://esm.sh/three@0.180.0?bundle');const{GLTFLoader}=await import('https://esm.sh/three@0.180.0/examples/jsm/loaders/GLTFLoader.js?bundle');
    const scene=new THREE.Scene();scene.background=new THREE.Color(0xf5f2e9);scene.fog=new THREE.FogExp2(0xf5f2e9,.035);const camera=new THREE.PerspectiveCamera(33,1,.05,120);camera.position.set(8.6,6.3,10.8);const renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:false,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(window.devicePixelRatio||1,1.7));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.08;
    const world=new THREE.Group();scene.add(world);scene.add(new THREE.HemisphereLight(0xffffff,0xc6c0b0,2.4));const sun=new THREE.DirectionalLight(0xffffff,5.3);sun.position.set(7,12,8);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-12;sun.shadow.camera.right=12;sun.shadow.camera.top=12;sun.shadow.camera.bottom=-12;scene.add(sun);const cool=new THREE.PointLight(0x7bdcff,7,16,2);cool.position.set(-5,4,-5);scene.add(cool);const warm=new THREE.PointLight(0xffb24e,5,13,2);warm.position.set(6,2.8,5);scene.add(warm);
    const floor=new THREE.Mesh(new THREE.PlaneGeometry(22,18),new THREE.MeshStandardMaterial({color:0xeeeae0,roughness:.96}));floor.rotation.x=-Math.PI/2;floor.receiveShadow=true;world.add(floor);const grid=new THREE.GridHelper(22,22,0x676d73,0xb8b8b2);grid.position.y=.012;grid.material.transparent=true;grid.material.opacity=.50;world.add(grid);const railMat=new THREE.MeshStandardMaterial({color:0xe6e1d6,metalness:.55,roughness:.38});[[0,.18,-6.6,18.6,.22,.13],[0,.18,6.6,18.6,.22,.13],[-9.25,.18,0,.13,.22,13.2],[9.25,.18,0,.13,.22,13.2]].forEach(([x,y,z,w,h,d])=>{const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),railMat);m.position.set(x,y,z);m.castShadow=true;world.add(m)});
    const redZone=new THREE.Mesh(new THREE.PlaneGeometry(3.7,12.8),new THREE.MeshBasicMaterial({color:0xff6e5b,transparent:true,opacity:.055,side:THREE.DoubleSide}));redZone.rotation.x=-Math.PI/2;redZone.position.set(-7.25,.018,0);world.add(redZone);const blueZone=redZone.clone();blueZone.material=redZone.material.clone();blueZone.material.color.set(0x61d8ff);blueZone.position.x=7.25;world.add(blueZone);
    const goalMat=new THREE.MeshStandardMaterial({color:0xd7d4cc,metalness:.72,roughness:.32}),accentRed=new THREE.MeshStandardMaterial({color:0xff655f,roughness:.48}),accentBlue=new THREE.MeshStandardMaterial({color:0x54cfff,roughness:.48}),darkMat=new THREE.MeshStandardMaterial({color:0x24282d,roughness:.58});[[-5.7,-3.5,accentRed],[-5.7,3.5,accentRed],[5.7,-3.5,accentBlue],[5.7,3.5,accentBlue]].forEach(([x,z,mat])=>{const g=new THREE.Group(),post=new THREE.Mesh(new THREE.CylinderGeometry(.12,.12,1.7,16),goalMat),ring=new THREE.Mesh(new THREE.TorusGeometry(.58,.08,12,40),mat),base=new THREE.Mesh(new THREE.CylinderGeometry(.42,.55,.13,20),darkMat);post.position.y=.86;post.castShadow=true;ring.rotation.x=Math.PI/2;ring.position.y=.58;ring.castShadow=true;base.position.y=.07;g.add(post,ring,base);g.position.set(x,0,z);world.add(g)});
    const particlesGeo=new THREE.BufferGeometry(),arr=new Float32Array(405);for(let i=0;i<135;i++){arr[i*3]=(Math.random()-.5)*24;arr[i*3+1]=.3+Math.random()*8;arr[i*3+2]=(Math.random()-.5)*19}particlesGeo.setAttribute('position',new THREE.BufferAttribute(arr,3));const particles=new THREE.Points(particlesGeo,new THREE.PointsMaterial({color:0x181b20,size:.045,transparent:true,opacity:.38}));scene.add(particles);
    const path=new THREE.CatmullRomCurve3([new THREE.Vector3(-7,.09,4.55),new THREE.Vector3(-5.6,.09,3.5),new THREE.Vector3(-3.5,.09,2.5),new THREE.Vector3(-1.4,.09,.55),new THREE.Vector3(.15,.09,-1.9),new THREE.Vector3(2.4,.09,-3.6),new THREE.Vector3(4.8,.09,-3.3),new THREE.Vector3(6,.09,-1.4),new THREE.Vector3(5,.09,1.15),new THREE.Vector3(2.9,.09,3.25),new THREE.Vector3(.7,.09,4.15)],false,'catmullrom',.38),pathTube=new THREE.Mesh(new THREE.TubeGeometry(path,180,.035,8,false),new THREE.MeshStandardMaterial({color:0xff514b,emissive:0x6b0805,emissiveIntensity:.55,roughness:.42}));pathTube.position.y=.035;world.add(pathTube);for(let i=0;i<9;i++){const p=path.getPointAt(i/8),d=new THREE.Mesh(new THREE.SphereGeometry(.085,16,16),new THREE.MeshStandardMaterial({color:0xff514b,emissive:0x8a0b06,emissiveIntensity:.4}));d.position.copy(p);d.position.y=.15;world.add(d)}
    const robotRoot=new THREE.Group();world.add(robotRoot);const fallback=(()=>{const r=new THREE.Group(),silver=new THREE.MeshStandardMaterial({color:0xcfd3d5,metalness:.78,roughness:.27}),steel=new THREE.MeshStandardMaterial({color:0x737b82,metalness:.85,roughness:.24}),orange=new THREE.MeshStandardMaterial({color:0xef9f2a,roughness:.42}),black=new THREE.MeshStandardMaterial({color:0x20242a,roughness:.64}),green=new THREE.MeshStandardMaterial({color:0x8cf05a,emissive:0x173e10,emissiveIntensity:.12,roughness:.45});const base=new THREE.Mesh(new THREE.BoxGeometry(2.15,.28,1.72),silver);base.position.y=.55;base.castShadow=true;r.add(base);for(const z of[-.68,.68])for(const x of[-.92,.92]){const w=new THREE.Mesh(new THREE.CylinderGeometry(.29,.29,.24,24),black);w.rotation.z=Math.PI/2;w.position.set(x,.42,z);w.castShadow=true;r.add(w)}for(const x of[-.74,.74]){const rail=new THREE.Mesh(new THREE.BoxGeometry(.12,1.75,.12),orange);rail.position.set(x,1.45,-.22);rail.rotation.z=x>0?-.13:.13;rail.castShadow=true;r.add(rail)}const cross=new THREE.Mesh(new THREE.BoxGeometry(1.7,.13,.14),silver);cross.position.set(0,2.24,-.2);r.add(cross);const brain=new THREE.Mesh(new THREE.BoxGeometry(.72,.36,.55),green);brain.position.set(0,.91,.2);brain.castShadow=true;r.add(brain);const intake=new THREE.Mesh(new THREE.BoxGeometry(1.7,.18,.64),orange);intake.position.set(0,.38,1.05);intake.rotation.x=-.24;intake.castShadow=true;r.add(intake);for(let i=-2;i<=2;i++){const beam=new THREE.Mesh(new THREE.BoxGeometry(1.92,.05,.05),steel);beam.position.set(0,.75+i*.25,-.68);r.add(beam)}return r})();robotRoot.add(fallback);
    try{const gltfLoader=new GLTFLoader(),compressedUrl='assets/models/vertex-pushback.glb.gz',plainUrl='assets/models/vertex-pushback.glb';let gltf;if('DecompressionStream'in window){const response=await fetch(compressedUrl);if(!response.ok)throw new Error(`CAD model fetch failed: ${response.status}`);loaderBar.style.width='62%';const decompressed=response.body.pipeThrough(new DecompressionStream('gzip')),buffer=await new Response(decompressed).arrayBuffer();loaderBar.style.width='90%';gltf=await new Promise((resolve,reject)=>gltfLoader.parse(buffer,'',resolve,reject))}else{gltf=await new Promise((resolve,reject)=>gltfLoader.load(plainUrl,resolve,xhr=>{if(xhr.total)loaderBar.style.width=`${Math.max(8,Math.min(92,(xhr.loaded/xhr.total)*92))}%`},reject))}robotRoot.remove(fallback);const model=gltf.scene;model.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;if(o.material)o.material.envMapIntensity=.55}});const box=new THREE.Box3().setFromObject(model),size=box.getSize(new THREE.Vector3()),center=box.getCenter(new THREE.Vector3());model.position.sub(center);model.scale.setScalar(2.55/Math.max(size.x,size.z,.001));const normalizedBox=new THREE.Box3().setFromObject(model);model.position.y-=normalizedBox.min.y;robotRoot.add(model);loaderBar.style.width='96%'}catch(err){console.warn('Real CAD model not available; using fallback.',err);warning.style.display='block'}
    const sensorRing=new THREE.Mesh(new THREE.RingGeometry(.72,.77,64),new THREE.MeshBasicMaterial({color:0x61d8ff,transparent:true,opacity:.34,side:THREE.DoubleSide,depthWrite:false}));sensorRing.rotation.x=-Math.PI/2;sensorRing.position.y=.035;robotRoot.add(sensorRing);robotRoot.add(new THREE.ArrowHelper(new THREE.Vector3(0,0,1),new THREE.Vector3(0,1,0),1.35,0x875cff,.28,.17));const camPath=new THREE.CatmullRomCurve3([new THREE.Vector3(8.9,6.6,10.6),new THREE.Vector3(6.2,4.4,7.2),new THREE.Vector3(1.8,3,5.3),new THREE.Vector3(-5.7,4.6,5.8),new THREE.Vector3(-8.1,6.9,-.4),new THREE.Vector3(-3.5,3.2,-7.2),new THREE.Vector3(3.6,2.7,-6),new THREE.Vector3(7.5,6.2,-1.8),new THREE.Vector3(5.2,7.2,7)],false,'catmullrom',.28);
    let mouseX=0,mouseY=0,currentProgress=0;shell.addEventListener('pointermove',e=>{const r=shell.getBoundingClientRect();mouseX=(e.clientX-r.left)/r.width-.5;mouseY=(e.clientY-r.top)/r.height-.5});shell.addEventListener('pointerleave',()=>{mouseX=0;mouseY=0});const resize=()=>{const r=shell.getBoundingClientRect();camera.aspect=Math.max(.3,r.width/Math.max(1,r.height));camera.updateProjectionMatrix();renderer.setSize(r.width,r.height,false)};new ResizeObserver(resize).observe(shell);resize();const readProgress=()=>{if(reduced||innerWidth<=900)return .18;const rect=hero.getBoundingClientRect(),travel=Math.max(1,hero.offsetHeight-innerHeight);return clamp(-rect.top/travel)},activateLabel=p=>{const idx=p<.24?0:p<.5?1:p<.76?2:3;stageLabels.forEach((el,i)=>el.classList.toggle('is-active',i===idx))},clock=new THREE.Clock(),target=new THREE.Vector3();function render(){const t=clock.getElapsedTime(),raw=readProgress();currentProgress+=(raw-currentProgress)*(reduced?.18:.065);const rp=clamp(currentProgress);activateLabel(rp);progressBar.style.width=`${rp*100}%`;const robotT=.025+smooth(clamp(rp/.93))*.90,p=path.getPointAt(robotT),tangent=path.getTangentAt(Math.min(.999,robotT+.001));robotRoot.position.set(p.x,.10+Math.sin(t*3.1)*.012,p.z);robotRoot.rotation.y=Math.atan2(tangent.x,tangent.z);sensorRing.scale.setScalar(1+Math.sin(t*2.6)*.09);sensorRing.material.opacity=.23+Math.sin(t*2.6)*.11;const c=camPath.getPointAt(clamp(rp*.98));camera.position.lerp(new THREE.Vector3(c.x+mouseX*.55,c.y-mouseY*.35,c.z+mouseX*.35),.075);target.lerp(new THREE.Vector3(p.x,p.y+1,p.z),.08);camera.lookAt(target);particles.rotation.y=t*.012;if(intro&&innerWidth>900){const fade=clamp((rp-.13)/.24);intro.style.opacity=String(1-fade*.72);intro.style.transform=`translateY(${-fade*18}px)`}renderer.render(scene,camera);requestAnimationFrame(render)}loaderBar.style.width='100%';setTimeout(()=>loaderEl.classList.add('is-ready'),220);render();
  }
  init3D().catch(err=>{console.error('3D scene failed to initialize',err);warning.textContent='3D renderer unavailable on this device';warning.style.display='block';loaderEl.classList.add('is-ready')});
}
